name: Integration Tests

on: [pull_request]

jobs:
  build:
    name: Build and test image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Build server image
      run: |
        docker build \
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
        --build-arg SOURCE_COMMIT=${GITHUB_SHA::8} \
        --no-cache \
        --rm \
        -t neicnordic/sda-db:${GITHUB_SHA::8} \
        .
    - name: Prepare for tests
      run: |
        mkdir -p data/{certs,data} && \
        sh .github/scripts/mk_certs.sh && \
        sudo chown -R 70:70 data && \
        sudo chmod 600 data/certs/pg.key && \
        docker network create ci
    - name: show data folder
      run: ls -la data && sudo cat data/certs/pg.crt
    - name: Start server
      run: |
        docker run -d \
        -e DB_LEGA_IN_PASSWORD="lega_in" \
        -e DB_LEGA_OUT_PASSWORD="lega_out" \
        -v "$PWD/data/certs:/var/lib/postgresql/certs" \
        -v "$PWD/data/data:/var/lib/postgresql/data" \
        --name db-server \
        --network ci \
        --read-only \
        neicnordic/sda-db:${GITHUB_SHA::8}
    - name: Vait for server to start
      run: |
        RETRY_TIMES=0
        until docker ps -f name=db-server | grep "(healthy)";
        do echo "waiting for server to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then
          docker logs db-server
          exit 1
        fi
        sleep 3;
        done
    - name: Write data
      run: |
        docker run --rm \
        --name client \
        --network ci \
        -v "$PWD/data/certs:/cert" \
        -u 70:70 \
        -e PGSSLMODE=verify-ca \
        -e PGSSLCERT="/cert/pg.crt" \
        -e PGSSLKEY="/cert/pg.key" \
        -e PGSSLROOTCERT="/cert/ca.crt" \
        neicnordic/pg-client:latest \
        postgresql://lega_in:lega_in@db-server:5432/lega \
        -c "INSERT INTO sda.files (submission_file_path, submission_user) VALUES ('test_file.c4gh', 'dummy')"
    - name: Read data
      run: |
        docker run --rm \
        --name client \
        --network ci \
        -v "$PWD/data/certs:/cert" \
        -u 70:70 \
        -e PGSSLMODE=verify-ca \
        -e PGSSLCERT="/cert/pg.crt" \
        -e PGSSLKEY="/cert/pg.key" \
        -e PGSSLROOTCERT="/cert/ca.crt" \
        neicnordic/pg-client:latest \
        postgresql://lega_in:lega_in@db-server:5432/lega \
        -c "SELECT submission_user, submission_file_path FROM sda.files" | grep test_file; \
        if [ $? == 1 ]; then
          exit 1
        fi
    - name: Stop and remove server
      run: |
        docker stop db-server &&\
        docker rm db-server
    - name: Restart server
      run: |
        docker run -d \
        -e DB_LEGA_IN_PASSWORD="lega_in" \
        -e DB_LEGA_OUT_PASSWORD="lega_out" \
        -v "$PWD/data/certs:/var/lib/postgresql/certs" \
        -v "$PWD/data/data:/var/lib/postgresql/data" \
        --name db-server \
        --network ci \
        --read-only \
        neicnordic/sda-db:${GITHUB_SHA::8}
    - name: Wait for server to restart
      run: |
        RETRY_TIMES=0
        until docker ps -f name=db-server | grep "(healthy)";
        do echo "waiting for server to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then
          docker logs db-server
          exit 1
        fi
        sleep 3;
        done
    - name: Verify data is intact
      run: |
        docker run --rm \
        --name client \
        --network ci \
        -v "$PWD/data/certs:/cert" \
        -u 70:70 \
        -e PGSSLMODE=verify-ca \
        -e PGSSLCERT="/cert/pg.crt" \
        -e PGSSLKEY="/cert/pg.key" \
        -e PGSSLROOTCERT="/cert/ca.crt" \
        neicnordic/pg-client:latest \
        postgresql://lega_in:lega_in@db-server:5432/lega \
        -c "SELECT submission_user, submission_file_path FROM sda.files" | grep test_file; \
        if [ $? == 1 ]; then
          exit 1
        fi
