name: Run database unit tests
on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Runs golang database tests in a postgres database container
    steps:
    - uses: docker/build-push-action@v4
      with:
        file: tests/Dockerfile
        tags: sda-db-tests:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: sda-db-tests:latest
        run: /tests/run_tests.sh
        shell: bash
