apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}
  labels:
    app: {{ template "sda.fullname" . }}
spec:
  ports:
    - name: amqps
      port: {{ ternary 5671 5672 (.Values.global.tls.enabled )}}
      targetPort: amqp
      protocol: TCP
    - name: epmd
      port: 4369
    - name: rabbitmq-dist
      port: 25672
    - name: management
      port: {{ ternary 15671 15672 (.Values.global.tls.enabled )}}
  selector:
    app: {{ template "sda.fullname" . }}

